# Decision Tree Regressor

## Importing the required libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor

## importing the dataset

In [3]:
data = pd.read_csv('datasets/Chocolates.csv')
data.head()

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04/01/2022,"$5,320.00",180
1,Van Tuxwell,India,85% Dark Bars,01/08/2022,"$7,896.00",94
2,Gigi Bohling,India,Peanut Butter Cubes,07/07/2022,"$4,501.00",91
3,Jan Morforth,Australia,Peanut Butter Cubes,27/04/2022,"$12,726.00",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24/02/2022,"$13,685.00",184

## Data Preprocessing

In [21]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['Sales Person'] = le.fit_transform(data['Sales Person'])
data['Country'] = le.fit_transform(data['Country'])
data['Product'] = le.fit_transform(data['Product'])
data.head()

   Sales Person  Country  Product        Date      Amount  Boxes Shipped
0            13        4       14  04/01/2022   $5,320.00            180
1            23        2        2  01/08/2022   $7,896.00             94
2             9        2       17  07/07/2022   $4,501.00             91
3            12        0       17  27/04/2022  $12,726.00            342
4            13        4       17  24/02/2022  $13,685.00            184

## Defining Target and Features

In [22]:
X = data.drop(['Boxes Shipped','Date','Amount'], axis=1)
y = data['Boxes Shipped']

## Splitting the data into Training set and Testing set

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((2625, 3), (657, 3), (2625,), (657,))

## MOdel Selection

In [24]:
regressor = DecisionTreeRegressor(random_state=42)

## Model Training

In [30]:
regressor.fit(X_train, y_train)

DecisionTreeRegressor(random_state=42)

## Prediction From the model

In [31]:
y_pred = regressor.predict(X_test)
y_pred

array([342.        , 444.5       , 200.        ,  71.5       ,
        21.        , 342.5       ,  37.5       ,  56.5       ,
        18.5       ,  36.        ,  69.5       , 107.        ,
       112.        ,  45.5       , 104.        ,  69.        ,
       395.5       ,  52.        , 238.5       , 120.        ,
        47.5       ,  45.        , 245.5       , 184.        ,
        81.5       , 427.        , 264.5       , 387.        ,
        43.        , 288.5       , 100.5       ,  45.        ,
       462.        ,  21.        ,  11.        ,  24.5       ,
       105.        ,  66.        ,  11.        , 151.        ,
        72.5       , 401.        , 151.5       , 232.        ,
        96.        ,  63.5       ,   7.        , 122.5       ,
        95.        ,  31.        , 447.        ,  70.        ,
       224.        , 216.        ,   8.5       ,   7.5       ,
       122.        , 332.        , 131.5       ,  86.        ,
       140.        , 240.        , 118.5       ,  21.        ,
       129.        , 104.        ,  33.        ,  66.        ,
        77.5       , 364.5       , 137.5       , 543.        ,
       253.5       , 260.66666667, 296.5       , 243.        ,
       251.        ,   7.        , 111.5       ,  87.        ,
       151.5       ,  96.        , 230.        , 215.5       ,
       445.        , 535.        , 338.5       , 236.        ,
       115.5       , 146.        , 287.        ,  24.        ,
        94.        , 175.        , 165.        , 264.5       ,
        14.33333333,  62.5       ,  76.        , 148.5       ,
       129.        ,  15.        , 223.        ,  78.        ,
       263.        , 740.        ,   3.        ,  12.        ,
       112.        , 507.5       , 166.        , 448.5       ,
       287.5       ,  85.        ,  80.        , 261.        ,
        22.        ,  92.5       , 245.5       , 152.5       ,
       339.        , 139.33333333, 141.5       , 235.        ,
       283.5       , 166.        , 178.        ,  65.5       ,
       140.        , 288.5       , 467.        , 130.        ,
        64.5       , 256.        , 157.        , 100.        ,
       327.        , 208.5       , 283.        , 157.        ,
        59.5       ,  61.        , 143.        ,  23.5       ,
       311.        , 106.        ,  25.        ,  99.        ,
        31.        , 125.5       ,  28.        ,  80.5       ,
        77.5       , 112.        , 449.        , 113.        ,
       272.        , 125.        , 223.        , 141.        ,
       210.        , 192.        , 220.5       , 187.        ,
        59.        , 225.        ,  97.        , 234.5       ,
       297.        , 134.        , 255.5       ,  98.        ,
        52.        , 200.        , 150.5       , 192.        ,
       198.5       , 126.        , 535.        , 130.        ,
       173.5       ,  12.        , 332.        ,  79.        ,
        59.        , 163.        ,  83.        , 146.        ,
       152.        ,  45.33333333,  41.        , 430.5       ,
       133.        ,  45.33333333, 107.        , 339.        ,
       223.        , 192.5       , 144.        , 426.5       ,
       110.33333333, 185.        ,  37.5       ,  45.        ,
        91.5       , 355.5       ,  85.5       , 140.5       ,
        23.        , 503.5       , 274.5       ,   1.        ,
       179.        , 104.        ,  70.5       , 429.        ,
         9.5       , 107.        , 110.        , 456.        ,
       139.33333333, 100.        , 309.5       , 208.        ,
       141.        , 239.5       ,  86.5       ,  79.5       ,
        41.        , 350.        ,  86.        , 299.        ,
       103.        ,  41.        , 288.5       ,  82.        ,
        38.5       , 340.        , 275.        , 129.        ,
       243.        , 211.        , 383.        , 171.        ,
       152.        , 241.        ,  23.        , 383.        ,
        73.        ,  43.5       , 141.        , 105.        ,
       348.        ,  20.        ,   7.        , 189.        ,
       245.5       , 216.        ,  98.5       ,  78.        ,
       264.        , 107.        ,  84.        , 163.        ,
       151.        , 321.5       ,  91.        , 139.5       ,
       356.        ,  66.5       , 558.5       , 245.5       ,
         4.        , 224.        ,  28.5       ,  23.5       ,
        85.        ,  20.        ,  96.5       , 103.5       ,
        21.5       , 272.        ,  71.        , 151.        ,
        60.        , 280.        , 394.5       , 147.        ,
       338.        ,  79.        , 153.        , 188.        ,
       124.        , 192.5       , 386.5       ,  41.5       ,
        53.        ,  80.        ,  84.5       , 197.5       ,
        55.5       , 445.        , 159.5       , 452.        ,
       140.5       , 176.        , 185.        , 104.        ,
        71.        ,  87.5       ,  70.5       , 423.        ,
       201.        , 522.        , 177.        , 254.        ,
       160.5       ,  21.5       ,  99.5       , 120.        ,
        57.        , 124.        , 106.5       ,  12.        ,
       140.        , 187.        , 456.        ,  89.        ,
        10.        , 333.        ,  32.5       , 199.        ,
       122.5       , 138.        , 243.        , 231.5       ,
       178.        , 149.        , 211.        ,  59.5       ,
        23.        , 149.        , 306.5       , 139.33333333,
        64.5       ,  33.5       ,  62.        , 157.        ,
        79.        , 138.        ,  57.        , 178.        ,
       263.5       , 243.        , 241.5       ,  66.        ,
       149.        ,   6.        , 159.5       , 275.5       ,
       107.5       ,  45.        , 131.5       ,  87.        ,
        59.        , 452.        ,  50.5       , 489.        ,
       153.        , 124.        , 178.5       ,  11.5       ,
       170.        , 220.        , 204.5       , 170.5       ,
       128.        , 110.        ,  91.5       ,  77.        ,
         4.        , 437.        , 185.5       ,  83.        ,
        93.        , 155.        , 140.        , 194.        ,
       297.5       , 188.        , 318.        , 141.5       ,
       467.        ,  45.5       , 209.        , 169.        ,
       249.        , 210.        , 287.        , 116.5       ,
        12.        , 353.5       ,  78.        , 262.5       ,
       160.        , 381.        ,  21.        , 307.5       ,
        54.5       , 401.5       , 398.5       , 176.        ,
        99.        ,  92.        , 117.5       , 113.        ,
       132.5       ,  24.        , 281.        ,  59.        ,
       186.        ,  45.        ,  76.5       , 119.        ,
       116.        ,  32.        , 245.5       ,  41.5       ,
        45.        , 287.        , 135.5       , 173.5       ,
       106.        , 118.        ,  69.        ,  45.33333333,
       445.        , 221.        ,  23.        , 124.        ,
       107.        ,  68.5       , 171.        ,  60.        ,
        97.        ,  40.        , 436.        ,   7.        ,
       134.        , 188.5       ,  27.5       , 263.5       ,
       175.5       , 105.        , 145.        , 165.        ,
        22.5       , 116.        , 113.5       , 142.5       ,
        77.        , 156.5       , 376.5       , 322.5       ,
       140.        , 156.5       , 130.        , 363.5       ,
         2.        , 291.        , 107.        ,  33.        ,
       239.        , 215.        ,  45.        , 235.5       ,
        30.        , 169.        , 166.5       , 181.5       ,
       209.5       , 414.        ,  11.        , 169.        ,
       496.        , 288.5       ,  87.        , 153.5       ,
       223.        , 110.33333333, 104.        , 489.        ,
        27.5       , 172.        ,  68.5       ,  57.5       ,
       449.        , 133.        , 264.        ,  85.        ,
       141.5       , 187.        , 154.        ,  12.        ,
        60.5       , 201.        , 267.        , 117.        ,
         2.        ,  43.        ,  93.        ,  78.        ,
       141.        ,  79.        , 161.5       ,  70.        ,
       317.5       ,  26.        ,  64.5       , 296.5       ,
       158.        , 173.        , 260.66666667,  12.        ,
        64.        , 151.        , 493.5       ,  62.        ,
        84.        , 153.        , 108.5       ,  70.        ,
        15.5       , 158.        , 136.        , 124.5       ,
       483.5       , 172.5       , 106.        ,  15.        ,
       232.        ,  70.5       , 154.        ,  31.        ,
       143.        ,  21.5       , 263.5       ,  21.        ,
       107.        , 178.        , 275.        ,  92.        ,
       287.        ,  57.5       , 101.        ,  35.        ,
       126.        ,  92.        ,  15.        , 262.5       ,
       153.        , 119.5       ,  14.33333333,  36.        ,
       481.        ,  71.        ,  24.5       ,  90.5       ,
       140.        , 285.        , 182.        , 156.        ,
        94.5       , 287.        , 310.5       , 146.        ,
       120.        ,  30.        ,  27.        , 166.        ,
       120.        ,  31.5       , 338.        ,  69.5       ,
        56.5       , 290.        , 308.5       ,   4.        ,
        68.        , 236.5       , 183.5       ,  23.5       ,
        59.        ,  93.        , 296.5       , 118.        ,
        45.        , 155.5       ,  26.        , 215.        ,
        76.5       , 125.5       , 423.        ,  28.        ,
       269.        , 420.        , 162.5       ,   2.        ,
       110.33333333, 347.        , 165.        , 350.        ,
       254.        ,  52.        , 134.        , 355.5       ,
       127.        , 287.        , 462.        , 138.        ,
       425.5       , 191.5       , 233.        ,  14.33333333,
       158.        ,  25.        , 348.        , 158.        ,
       190.5       , 233.        , 400.5       , 230.5       ,
       140.        , 260.66666667, 211.        ,  18.5       ,
        99.        ,   2.        , 117.        , 202.5       ,
       176.5       ,  24.        ,  66.        , 311.        ,
       198.        , 118.        ,  21.        , 119.        ,
        94.        , 278.        , 329.        , 103.5       ,
       170.        , 142.        ,  80.        , 104.5       ,
       249.        ])

## Model Evaluations

In [32]:
r2_score = regressor.score(X_test, y_test)
r2_score

0.9458895463683387